mysite/house/urls.py
from django.urls import path
from . import views

app_name = 'house'
urlpatterns = [
    path('', views.house, name='house'),
    path('<int:activity_id>/', views.detail, name='detail'),
  
    path('<int:activity_id>/about/', views.about, name='about'),
   
    path('<int:activity_id>/category/', views.category, name='category'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('house.urls')),
    path('admin/', admin.site.urls),
]

mysite/house/models.py
from django.db import models
# Create your models here.
class Activities(models.Model):
    activity_text = models.CharField(max_length=200)
    detail_text = models.TextField(max_length=1000)
    category_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published')
    #activity_text = "reading"
    def __str__(self):
        return self.activity_text
#class Details(models.Model):
    #detail_text = "You can pick up a book from your bookshelf or look up an ebook online" 
    def __str__(self):
        return self.detail_text
    
    #category_text = "leisure, alone, relaxing"
    def __str__(self):
        return self.category_text
    
    #pub_date = 05012023
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    class Meta:
        verbose_name = "The Activity"
        verbose_name_plural = "Activity"

mysite/house/views.py
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Activities
from django.shortcuts import get_object_or_404, render

def detail(request, activity_id):
    activity = get_object_or_404(Activities, pk=activity_id)
    return render(request, 'house/detail.html', {'activity': activity})

    #return HttpResponse("You're looking at activity %s." % activity_id)
    
    #try:
        #activity = Activities.objects.get(pk=activity_id)
    #except Activities.DoesNotExist:
        #raise Http404("Activity does not exist")
    #return render(request, 'house/detail.html', {'activity': activity})
    
def about(request, activity_id):
    response = "You're looking at the description of activity %s."
    return HttpResponse(response % activity_id)
def category(request, activity_id):
    return HttpResponse("You're categorising activity %s." % activity_id)
#def index(request):
    #return HttpResponse("Hello world!")
def house(request):
  #return HttpResponse(template.render())
    #context = {}
    activities = Activities.objects.all()
    #using shortcut from tutorial03
    #template = loader.get_template('house/myfirst.html')
    #context['activities'] = activities
    context = {
        'activities': activities,
    }
    #changed from return render(request, 'house.html', context), also created a house directory inside templates to put myfirst.html in
    return render(request, 'house/myfirst.html', context)
    #return HttpResponse(template.render(context, request))
    
    
    
    

mysite/house/templates/house/detail.html
<!DOCTYPE html>
<h1>{{ activity.activity_text }}</h1>
<ul>
<li><p>Detail:</p>{{ activity.detail_text }}</li>
<li><p>Category:</p>{{ activity.category_text }}</li>
<li><p>Published at:</p>{{ activity.pub_date }}</li>
</ul>

mysite/house/templates/house/myfirst.html
<!DOCTYPE html>
 <!--The viewport is the user's visible area of a web page. It varies with the device - it will be smaller on a mobile phone than on a computer screen.(might need to paste on a different line in this document.)-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<html>
<head>
    {% load static %}
    <title>Page Title</title>
    <link rel="stylesheet" href="{% static 'house/example.css' %}">

<head>

<body>
    <h1>Activities to do at home</h1>
    <p>Welcome to my first Django project!</p>
    <p>These are some activities to do at home</p>
{% if activities %}
    <ul>
    {% for activity in activities %}
        <li><a href="{% url 'house:detail' activity.id %}">{{ activity.activity_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>This is not a valid activity.</p>
{% endif %}
</body>
</html>